<?php
/**
 * Fix action: llms.txt.
 *
 * Wraps the existing WellKnown\LlmsTxt generator. Apply = regenerate + save.
 * Rollback = delete the stored options (the virtual route returns a minimal
 * placeholder document in that case — see LlmsTxt::serve()).
 *
 * When another plugin (Rank Math) or a physical file owns /llms.txt, the fix
 * enters "covered" mode: Audit checks the external output against GEO Forge's
 * basic standard, Cover (override) backs up + removes the physical file or
 * force-registers the virtual route, and Ignore accepts the status quo.
 *
 * @package GEO_Forge
 */

namespace GEO_Forge\Fixer\Actions;

use GEO_Forge\Compat\SeoDetector;
use GEO_Forge\Fixer\FixInterface;
use GEO_Forge\WellKnown\LlmsTxt;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class LlmsTxtFix implements FixInterface {

	private const AUDIT_OPTION = 'geo_forge_audit_llms_txt';
	private const OVERRIDE_OPTION = 'geo_forge_override_llms_txt';
	private const IGNORE_OPTION   = 'geo_forge_ignored_llms_txt';
	private const PHYSICAL_FILE   = 'llms.txt';

	public function get_id(): string {
		return 'llms_txt';
	}

	public function get_label(): string {
		return __( 'Generate / update llms.txt', 'geo-forge' );
	}

	public function get_description(): string {
		return __( 'Create /llms.txt from current store data so AI agents can discover your products.', 'geo-forge' );
	}

	public function get_risk_level(): string {
		return 'none'; // writes to a virtual route, doesn't touch existing content
	}

	public function get_priority(): int {
		return 1;
	}

	public function get_check_ids(): array {
		return array( 'llms_txt', 'llms_txt_quality' );
	}

	public function get_status(): string {
		if ( 'yes' === get_option( self::IGNORE_OPTION, '' ) ) {
			return 'ignored';
		}

		$owner = SeoDetector::llms_txt_owner();
		if ( 'geo-forge' !== $owner && 'yes' !== get_option( self::OVERRIDE_OPTION, '' ) ) {
			return 'covered';
		}

		return '' === LlmsTxt::get_current() ? 'pending' : 'applied';
	}

	public function apply(): array {
		if ( 'covered' === $this->get_status() ) {
			return array(
				'success' => false,
				'message' => sprintf(
					/* translators: %s: owner label */
					__( 'llms.txt is managed by %s — run Audit first, then Cover to override.', 'geo-forge' ),
					SeoDetector::owner_label( SeoDetector::llms_txt_owner() )
				),
			);
		}

		$content = LlmsTxt::regenerate_all();

		return array(
			'success'      => true,
			'message'      => __( 'llms.txt generated and saved.', 'geo-forge' ),
			'score_change' => 7, // Matches design doc estimate; GEO KAMI will confirm on verify.
		);
	}

	public function rollback(): array {
		// Undo override/ignore first, and clean the stored audit.
		delete_option( self::OVERRIDE_OPTION );
		delete_option( self::IGNORE_OPTION );
		delete_option( self::AUDIT_OPTION );

		if ( 'geo-forge' !== SeoDetector::llms_txt_owner() ) {
			// Restore a physical file we backed up during Cover.
			$backup = ABSPATH . self::PHYSICAL_FILE . '.geo-forge-backup';
			if ( file_exists( $backup ) ) {
				// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_rename
				rename( $backup, ABSPATH . self::PHYSICAL_FILE );
			}
			return array(
				'success' => true,
				'message' => __( 'Override removed — ownership returned to the original provider.', 'geo-forge' ),
			);
		}

		delete_option( 'geo_forge_llms_txt' );
		delete_option( 'geo_forge_llms_full_txt' );
		delete_option( 'geo_forge_llms_txt_source' );
		return array(
			'success' => true,
			'message' => __( 'llms.txt removed.', 'geo-forge' ),
		);
	}

	public function verify(): array {
		return array(); // handled by Fixer engine via /verify API
	}

	/**
	 * Audit the externally-managed /llms.txt against GEO Forge's basic
	 * standard. Never writes content.
	 */
	public function audit(): array {
		$owner = SeoDetector::llms_txt_owner();
		if ( 'geo-forge' === $owner ) {
			$result = array(
				'pass'    => true,
				'message' => __( 'llms.txt is already generated by GEO Forge.', 'geo-forge' ),
			);
			$this->store_audit( $result );
			return array( 'success' => true ) + $result;
		}

		$content = $this->fetch_owned_content( $owner );
		if ( null === $content ) {
			$result = array(
				'pass'    => false,
				'message' => __( 'Could not read the llms.txt currently being served — audit inconclusive.', 'geo-forge' ),
			);
			$this->store_audit( $result );
			return array( 'success' => true ) + $result;
		}

		$has_h1    = (bool) preg_match( '/^#\s+/m', $content );
		$link_count = preg_match_all( '/\]\(/s', $content );
		$has_sec   = (bool) preg_match( '/^##\s+/m', $content );
		$has_prod  = (bool) preg_match( '/(?i)(\/product[s]?\/|\/shop\/|##\s*products|##\s*core\s*pages)/', $content );

		$failures = array();
		if ( ! $has_h1 ) {
			$failures[] = 'H1 title';
		}
		if ( $link_count < 3 ) {
			$failures[] = '3+ links';
		}
		if ( ! $has_sec ) {
			$failures[] = 'sections';
		}
		if ( ! $has_prod ) {
			$failures[] = 'product/shop links';
		}

		$result = array(
			'pass'    => empty( $failures ),
			'message' => empty( $failures )
				? __( 'The llms.txt served by the current owner meets GEO Forge’s basic standard.', 'geo-forge' )
				/* translators: %s: missing items */
				: sprintf( __( 'Below GEO Forge standard — missing: %s.', 'geo-forge' ), implode( ', ', $failures ) ),
		);
		$this->store_audit( $result );
		return array( 'success' => true ) + $result;
	}

	/**
	 * Take over /llms.txt. Backs up + removes a physical file, force-
	 * registers the virtual route, and regenerates content.
	 */
	public function cover(): array {
		$owner = SeoDetector::llms_txt_owner();

		if ( 'physical' === $owner ) {
			$file = ABSPATH . self::PHYSICAL_FILE;
			if ( file_exists( $file ) ) {
				// Backing up needs read on the file; unlinking needs write on
				// the containing directory (not the file itself) — e.g. a
				// root-owned 644 llms.txt in a www-writable web root can be
				// taken over even though PHP cannot write the file.
				if ( ! is_readable( $file ) || ! is_writable( dirname( $file ) ) ) {
					return array(
						'success' => false,
						'message' => __( 'The physical llms.txt cannot be removed by the server — the file must be readable and the site root writable. Remove it via FTP/panel first, then run Cover again.', 'geo-forge' ),
					);
				}
				$backup = $file . '.geo-forge-backup';
				if ( ! file_exists( $backup ) ) {
					// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_copy
					copy( $file, $backup );
				}
				// phpcs:ignore WordPress.WP.AlternativeFunctions.unlink
				unlink( $file );
			}
		}

		update_option( self::OVERRIDE_OPTION, 'yes', false );
		delete_option( self::IGNORE_OPTION );
		LlmsTxt::regenerate_all();

		return array(
			'success' => true,
			'status'  => 'applied',
			'message' => 'physical' === $owner
				? __( 'Physical llms.txt backed up and removed — /llms.txt is now served by GEO Forge.', 'geo-forge' )
				: __( 'GEO Forge now generates /llms.txt (override).', 'geo-forge' ),
		);
	}

	/**
	 * Accept the external output — GEO Forge will not touch /llms.txt.
	 */
	public function ignore(): array {
		update_option( self::IGNORE_OPTION, 'yes', false );
		return array(
			'success' => true,
			'status'  => 'ignored',
			'message' => __( 'Ignored — GEO Forge will not touch the llms.txt managed elsewhere.', 'geo-forge' ),
		);
	}

	/* =================================================================
	 * Helpers
	 * ================================================================ */

	private function store_audit( array $result ): void {
		update_option( self::AUDIT_OPTION, array(
			'pass'       => (bool) $result['pass'],
			'message'    => (string) $result['message'],
			'checked_at' => current_time( 'mysql' ),
		), false );
	}

	private function fetch_owned_content( string $owner ): ?string {
		if ( 'physical' === $owner ) {
			$file = ABSPATH . self::PHYSICAL_FILE;
			if ( file_exists( $file ) && is_readable( $file ) ) {
				// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_read_file_get_contents
				return (string) file_get_contents( $file );
			}
			return null;
		}

		$resp = wp_remote_get( home_url( '/' . self::PHYSICAL_FILE ), array(
			'timeout'    => 10,
			'redirection' => 3,
		) );
		if ( is_wp_error( $resp ) || 200 !== (int) wp_remote_retrieve_response_code( $resp ) ) {
			return null;
		}
		return (string) wp_remote_retrieve_body( $resp );
	}
}
