<?php
/**
 * llms.txt generator.
 *
 * Produces the llms.txt (curated) and llms-full.txt (complete product index)
 * documents from current WooCommerce / WordPress data, and stores them as
 * non-autoloaded options. The Router serves them as virtual files.
 *
 * Content is only rebuilt by an explicit action — the editor, the Fixer,
 * or the scheduled job — never on every request.
 *
 * @package GEO_Forge
 */

namespace GEO_Forge\WellKnown;

use GEO_Forge\Log\Logger;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class LlmsTxt {

	private const OPTION        = 'geo_forge_llms_txt';
	private const OPTION_FULL   = 'geo_forge_llms_full_txt';
	private const SOURCE_OPTION = 'geo_forge_llms_txt_source';

	/**
	 * Serve the stored llms.txt. Returns a spec-valid minimal document when
	 * nothing has been generated yet — never runs heavy queries on demand.
	 */
	public static function serve(): string {
		$content = (string) get_option( self::OPTION, '' );

		if ( '' === $content ) {
			$content = self::minimal();
		}

		/**
		 * Filter the served llms.txt content.
		 *
		 * Lets site owners or other plugins append/remove sections without
		 * editing the stored option.
		 *
		 * @param string $content The markdown content about to be served.
		 */
		return (string) apply_filters( 'geo_forge_llms_txt_content', $content );
	}

	/**
	 * Serve the stored llms-full.txt (complete product index).
	 */
	public static function serve_full(): string {
		$content = (string) get_option( self::OPTION_FULL, '' );

		if ( '' === $content ) {
			$content = self::minimal_full();
		}

		/**
		 * Filter the served llms-full.txt content.
		 *
		 * @param string $content The markdown content about to be served.
		 */
		return (string) apply_filters( 'geo_forge_llms_full_txt_content', $content );
	}

	/**
	 * Generate fresh curated content from current WooCommerce / WordPress data.
	 * Returns the markdown string. Does NOT persist — caller decides.
	 */
	public static function generate(): string {
		$name        = (string) get_bloginfo( 'name' );
		$description = (string) get_bloginfo( 'description' );
		$out         = "# {$name}\n";
		$out        .= "> {$description}\n\n";

		$out .= self::section_products();
		$out .= self::section_categories();
		$out .= self::section_pages();
		$out .= self::section_resources();
		$out .= self::section_contact();

		$out .= "\n---\n";
		$out .= 'Generated by GEO Forge on ' . current_time( 'Y-m-d' ) . ".\n";

		return $out;
	}

	/**
	 * Generate the complete product index (llms-full.txt).
	 */
	public static function generate_full(): string {
		if ( ! function_exists( 'wc_get_products' ) ) {
			return self::minimal_full();
		}

		$name = (string) get_bloginfo( 'name' );
		$out  = "# {$name}\n";
		$out .= "> Complete product index generated by GEO Forge.\n\n";
		$out .= "## Products\n\n";

		$count   = 0;
		$offset  = 0;
		$batch   = 100;

		do {
			$products = wc_get_products( array(
				'limit'   => $batch,
				'offset'  => $offset,
				'status'  => 'publish',
				'orderby' => 'title',
				'order'   => 'ASC',
			) );

			if ( empty( $products ) ) {
				break;
			}

			foreach ( $products as $product ) {
				$out .= self::product_line( $product );
				$count++;
			}

			$offset += $batch;
		} while ( count( $products ) === $batch );

		if ( 0 === $count ) {
			$out .= "_No published products yet._\n";
		}

		$out .= "\n---\n";
		$out .= 'Generated by GEO Forge on ' . current_time( 'Y-m-d' ) . ".\n";

		return $out;
	}

	/**
	 * Generate and persist llms.txt. Marks the content as auto-generated.
	 */
	public static function regenerate(): string {
		$content = self::generate();
		update_option( self::OPTION, $content, false );
		update_option( self::SOURCE_OPTION, 'generated', false );

		Logger::info(
			'llms.txt regenerated.',
			array( 'bytes' => strlen( $content ) )
		);

		return $content;
	}

	/**
	 * Generate and persist llms-full.txt.
	 */
	public static function regenerate_full(): string {
		$content = self::generate_full();
		update_option( self::OPTION_FULL, $content, false );

		Logger::info(
			'llms-full.txt regenerated.',
			array( 'bytes' => strlen( $content ) )
		);

		return $content;
	}

	/**
	 * Save user-edited content (from the admin editor).
	 * Marks the content as manual so scheduled runs don't overwrite it.
	 */
	public static function save( string $content ): void {
		// Keep the content, but trim trailing whitespace per line.
		$lines   = array_map( 'rtrim', explode( "\n", $content ) );
		$content = implode( "\n", $lines );

		update_option( self::OPTION, $content, false );
		update_option( self::SOURCE_OPTION, 'manual', false );
		Logger::info( 'llms.txt saved from editor.', array( 'bytes' => strlen( $content ) ) );
	}

	/**
	 * Get the currently stored content (for the admin editor).
	 */
	public static function get_current(): string {
		return (string) get_option( self::OPTION, '' );
	}

	/**
	 * Get the currently stored llms-full.txt content.
	 */
	public static function get_current_full(): string {
		return (string) get_option( self::OPTION_FULL, '' );
	}

	/**
	 * Was llms.txt last written by the user via the editor?
	 */
	public static function is_manual(): bool {
		return 'manual' === get_option( self::SOURCE_OPTION, '' );
	}

	/**
	 * A spec-valid placeholder shown until the first generation runs.
	 */
	public static function minimal(): string {
		$name = (string) get_bloginfo( 'name' );
		$out  = "# {$name}\n";
		$out .= "> " . (string) get_bloginfo( 'description' ) . "\n\n";
		$out .= "_llms.txt will be generated by GEO Forge. Use the Optimizations page or wait for the scheduled job._\n";
		return $out;
	}

	/**
	 * Placeholder for llms-full.txt.
	 */
	public static function minimal_full(): string {
		$name = (string) get_bloginfo( 'name' );
		$out  = "# {$name}\n";
		$out .= "> Complete product index will be generated by GEO Forge.\n\n";
		$out .= "_llms-full.txt will be generated by the scheduled job._\n";
		return $out;
	}

	/**
	 * Is there a physical llms.txt in the web root? If so the web server
	 * serves it directly and our virtual route never runs.
	 */
	public static function physical_file_exists(): bool {
		return file_exists( ABSPATH . 'llms.txt' );
	}

	/* =================================================================
	 * Section builders
	 * ================================================================ */

	private static function section_products(): string {
		if ( ! function_exists( 'wc_get_products' ) ) {
			return "## Products\n\n_WooCommerce not active._\n\n";
		}

		$products = wc_get_products( array(
			'limit'   => 20,
			'orderby' => 'popularity',
			'status'  => 'publish',
		) );

		if ( empty( $products ) ) {
			return "## Products\n\n_No published products yet._\n\n";
		}

		$out = "## Products\n\n";
		foreach ( $products as $product ) {
			$out .= self::product_line( $product );
		}
		$out .= "\n";

		return $out;
	}

	/**
	 * Format a single product as a markdown bullet.
	 */
	private static function product_line( $product ): string {
		$permalink = (string) $product->get_permalink();
		$name      = self::md_link_text( (string) $product->get_name() );
		$short     = wp_strip_all_tags( (string) $product->get_short_description() );
		$short     = wp_trim_words( $short, 40, '…' );
		$price     = $product->get_price();

		$line = "- [{$name}]({$permalink})";
		if ( '' !== $short ) {
			$line .= " — {$short}";
		}
		if ( '' !== $price ) {
			$line .= ' (' . $price . ' ' . get_woocommerce_currency() . ')';
		}

		return $line . "\n";
	}

	private static function section_categories(): string {
		if ( ! taxonomy_exists( 'product_cat' ) ) {
			return '';
		}

		$terms = get_terms( array(
			'taxonomy'   => 'product_cat',
			'hide_empty' => true,
			'number'     => 20,
			'orderby'    => 'count',
			'order'      => 'DESC',
		) );

		if ( is_wp_error( $terms ) || empty( $terms ) ) {
			return '';
		}

		$out = "## Categories\n\n";
		foreach ( $terms as $term ) {
			$link = get_term_link( $term );
			if ( is_wp_error( $link ) ) {
				continue;
			}
			$desc = $term->description ? ' — ' . wp_strip_all_tags( $term->description ) : '';
			$out .= '- [' . self::md_link_text( (string) $term->name ) . '](' . $link . "){$desc}\n";
		}
		$out .= "\n";

		return $out;
	}

	private static function section_pages(): string {
		$pages = get_pages( array(
			'sort_column' => 'menu_order',
			'sort_order'  => 'ASC',
			'number'      => 10,
		) );

		if ( empty( $pages ) ) {
			return '';
		}

		$out = "## Pages\n\n";
		foreach ( $pages as $page ) {
			$out .= '- [' . self::md_link_text( (string) $page->post_title ) . '](' . get_permalink( $page ) . ")\n";
		}
		$out .= "\n";

		return $out;
	}

	/**
	 * Helpful pointers: sitemap + the complete product index.
	 */
	private static function section_resources(): string {
		$out  = "## Site\n\n";
		$out .= '- Sitemap: ' . self::sitemap_url() . "\n";
		$out .= '- Full product list: ' . home_url( '/llms-full.txt' ) . "\n\n";
		return $out;
	}

	private static function section_contact(): string {
		$email = (string) get_option( 'admin_email', '' );
		$out   = "## Contact\n\n";
		if ( '' !== $email ) {
			$out .= "- Email: {$email}\n";
		}
		$out .= '- Store: ' . home_url() . "\n\n";
		return $out;
	}

	/**
	 * Best available sitemap URL: SEO plugins first, WP core sitemaps last.
	 */
	private static function sitemap_url(): string {
		if ( defined( 'RANK_MATH_VERSION' ) || defined( 'WPSEO_VERSION' ) ) {
			return home_url( '/sitemap_index.xml' );
		}
		return home_url( '/wp-sitemap.xml' );
	}

	/**
	 * Escape markdown link-text metacharacters so store names can't break
	 * the generated links.
	 */
	private static function md_link_text( string $text ): string {
		return str_replace( array( '[', ']' ), array( '\[', '\]' ), $text );
	}
}
