<?php
/**
 * llms.txt generator.
 *
 * Produces the llms.txt (curated), llms-full.txt (complete product index)
 * and optional llms-{locale}.txt (multilingual) documents from current
 * WooCommerce / WordPress data, and stores them as non-autoloaded options.
 * The Router serves them as virtual files.
 *
 * Content is only rebuilt by an explicit action — the editor, the Fixer,
 * or the scheduled job — never on every request.
 *
 * @package GEO_Forge
 */

namespace GEO_Forge\WellKnown;

use GEO_Forge\Log\Logger;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class LlmsTxt {

	private const OPTION        = 'geo_forge_llms_txt';
	private const OPTION_FULL   = 'geo_forge_llms_full_txt';
	private const SOURCE_OPTION = 'geo_forge_llms_txt_source';

	/**
	 * Serve the stored llms.txt. Returns a spec-valid minimal document when
	 * nothing has been generated yet — never runs heavy queries on demand.
	 */
	public static function serve(): string {
		$content = (string) get_option( self::OPTION, '' );

		if ( '' === $content ) {
			$content = self::minimal();
		}

		/**
		 * Filter the served llms.txt content.
		 *
		 * Lets site owners or other plugins append/remove sections without
		 * editing the stored option.
		 *
		 * @param string $content The markdown content about to be served.
		 */
		return (string) apply_filters( 'geo_forge_llms_txt_content', $content );
	}

	/**
	 * Serve the stored llms-full.txt (complete product index).
	 */
	public static function serve_full(): string {
		$content = (string) get_option( self::OPTION_FULL, '' );

		if ( '' === $content ) {
			$content = self::minimal_full();
		}

		/**
		 * Filter the served llms-full.txt content.
		 *
		 * @param string $content The markdown content about to be served.
		 */
		return (string) apply_filters( 'geo_forge_llms_full_txt_content', $content );
	}

	/**
	 * Serve a language-specific llms-{locale}.txt.
	 *
	 * @param string $locale Validated locale, e.g. 'zh_CN' or 'ja'.
	 */
	public static function serve_lang( string $locale ): string {
		$content = (string) get_option( 'geo_forge_llms_txt_' . $locale, '' );

		if ( '' === $content ) {
			$content = self::minimal_lang( $locale );
		}

		return (string) apply_filters( 'geo_forge_llms_txt_content', $content );
	}

	/**
	 * Generate fresh curated content from current WooCommerce / WordPress data.
	 * Returns the markdown string. Does NOT persist — caller decides.
	 */
	public static function generate(): string {
		$name        = (string) get_bloginfo( 'name' );
		$description = (string) get_bloginfo( 'description' );
		$out         = "# {$name}\n";
		$out        .= "> {$description}\n\n";

		$out .= self::section_products();
		$out .= self::section_categories();
		$out .= self::section_pages();
		$out .= self::section_resources();
		$out .= self::section_contact();

		$out .= "\n---\n";
		$out .= 'Generated by GEO Forge on ' . current_time( 'Y-m-d' ) . ".\n";

		return $out;
	}

	/**
	 * Generate a language-specific llms-{locale}.txt. Store data (product
	 * names, descriptions) is emitted as-is; section headings and store
	 * URLs are localized where the multilingual plugin exposes them.
	 *
	 * @param string $locale Validated locale, e.g. 'zh_CN' or 'ja'.
	 */
	public static function generate_lang( string $locale ): string {
		$h    = self::lang_headings( $locale );
		$home = self::lang_home_url( $locale );
		$name = (string) get_bloginfo( 'name' );
		$desc = (string) get_bloginfo( 'description' );

		$out  = "# {$name}\n";
		$out .= "> {$desc}\n\n";

		$out .= self::section_products( $h['products'] );
		$out .= self::section_categories( $h['categories'] );
		$out .= self::section_pages( $h['pages'] );
		$out .= self::section_resources( $h['site'], $home, $locale );
		$out .= self::section_contact( $h['contact'], $home );

		$out .= "\n---\n";
		$out .= 'Generated by GEO Forge on ' . current_time( 'Y-m-d' ) . ".\n";

		return $out;
	}

	/**
	 * Generate the complete product index (llms-full.txt).
	 */
	public static function generate_full(): string {
		if ( ! function_exists( 'wc_get_products' ) ) {
			return self::minimal_full();
		}

		$name = (string) get_bloginfo( 'name' );
		$out  = "# {$name}\n";
		$out .= "> Complete product index generated by GEO Forge.\n\n";
		$out .= "## Products\n\n";

		$count  = 0;
		$offset = 0;
		$batch  = 100;

		do {
			$products = wc_get_products( array(
				'limit'   => $batch,
				'offset'  => $offset,
				'status'  => 'publish',
				'orderby' => 'title',
				'order'   => 'ASC',
			) );

			if ( empty( $products ) ) {
				break;
			}

			foreach ( $products as $product ) {
				$out .= self::product_line( $product );
				$count++;
			}

			$offset += $batch;
		} while ( count( $products ) === $batch );

		if ( 0 === $count ) {
			$out .= "_No published products yet._\n";
		}

		$out .= "\n---\n";
		$out .= 'Generated by GEO Forge on ' . current_time( 'Y-m-d' ) . ".\n";

		return $out;
	}

	/**
	 * Generate and persist llms.txt. Marks the content as auto-generated.
	 */
	public static function regenerate(): string {
		$content = self::generate();
		update_option( self::OPTION, $content, false );
		update_option( self::SOURCE_OPTION, 'generated', false );

		Logger::info(
			'llms.txt regenerated.',
			array( 'bytes' => strlen( $content ) )
		);

		return $content;
	}

	/**
	 * Generate and persist llms-full.txt.
	 */
	public static function regenerate_full(): string {
		$content = self::generate_full();
		update_option( self::OPTION_FULL, $content, false );

		Logger::info(
			'llms-full.txt regenerated.',
			array( 'bytes' => strlen( $content ) )
		);

		return $content;
	}

	/**
	 * Generate and persist a language-specific llms-{locale}.txt.
	 *
	 * @param string $locale Validated locale, e.g. 'zh_CN' or 'ja'.
	 */
	public static function regenerate_lang( string $locale ): string {
		$content = self::generate_lang( $locale );
		update_option( 'geo_forge_llms_txt_' . $locale, $content, false );

		Logger::info(
			'llms-' . $locale . '.txt regenerated.',
			array( 'bytes' => strlen( $content ) )
		);

		return $content;
	}

	/**
	 * Regenerate the curated, full and every configured language variant.
	 */
	public static function regenerate_all(): string {
		$content = self::regenerate();
		self::regenerate_full();
		foreach ( self::languages() as $locale ) {
			self::regenerate_lang( $locale );
		}
		return $content;
	}

	/**
	 * Save user-edited content (from the admin editor).
	 * Marks the content as manual so scheduled runs don't overwrite it.
	 */
	public static function save( string $content ): void {
		// Keep the content, but trim trailing whitespace per line.
		$lines   = array_map( 'rtrim', explode( "\n", $content ) );
		$content = implode( "\n", $lines );

		update_option( self::OPTION, $content, false );
		update_option( self::SOURCE_OPTION, 'manual', false );
		Logger::info( 'llms.txt saved from editor.', array( 'bytes' => strlen( $content ) ) );
	}

	/**
	 * Get the currently stored content (for the admin editor).
	 */
	public static function get_current(): string {
		return (string) get_option( self::OPTION, '' );
	}

	/**
	 * Get the currently stored llms-full.txt content.
	 */
	public static function get_current_full(): string {
		return (string) get_option( self::OPTION_FULL, '' );
	}

	/**
	 * Was llms.txt last written by the user via the editor?
	 */
	public static function is_manual(): bool {
		return 'manual' === get_option( self::SOURCE_OPTION, '' );
	}

	/**
	 * Configured extra locales (e.g. ['zh_CN', 'ja']), validated.
	 *
	 * @return string[]
	 */
	public static function languages(): array {
		$raw   = (string) get_option( 'geo_forge_llms_languages', '' );
		$langs = array();

		foreach ( explode( ',', $raw ) as $piece ) {
			$locale = trim( $piece );
			if ( preg_match( '/^[a-z]{2}(_[A-Z]{2})?$/', $locale ) ) {
				$langs[] = $locale;
			}
		}

		return array_values( array_unique( $langs ) );
	}

	/**
	 * A spec-valid placeholder shown until the first generation runs.
	 */
	public static function minimal(): string {
		$name = (string) get_bloginfo( 'name' );
		$out  = "# {$name}\n";
		$out .= "> " . (string) get_bloginfo( 'description' ) . "\n\n";
		$out .= "_llms.txt will be generated by GEO Forge. Use the Optimizations page or wait for the scheduled job._\n";
		return $out;
	}

	/**
	 * Placeholder for llms-full.txt.
	 */
	public static function minimal_full(): string {
		$name = (string) get_bloginfo( 'name' );
		$out  = "# {$name}\n";
		$out .= "> Complete product index will be generated by GEO Forge.\n\n";
		$out .= "_llms-full.txt will be generated by the scheduled job._\n";
		return $out;
	}

	/**
	 * Placeholder for a language variant.
	 */
	public static function minimal_lang( string $locale ): string {
		$name = (string) get_bloginfo( 'name' );
		$out  = "# {$name}\n";
		$out .= "> " . (string) get_bloginfo( 'description' ) . "\n\n";
		$out .= "_llms-{$locale}.txt will be generated by GEO Forge._\n";
		return $out;
	}

	/**
	 * Is there a physical llms.txt in the web root? If so the web server
	 * serves it directly and our virtual route never runs.
	 */
	public static function physical_file_exists(): bool {
		return file_exists( ABSPATH . 'llms.txt' );
	}

	/* =================================================================
	 * Section builders
	 * ================================================================ */

	private static function section_products( string $heading = 'Products' ): string {
		if ( ! function_exists( 'wc_get_products' ) ) {
			return "## {$heading}\n\n_WooCommerce not active._\n\n";
		}

		$products = wc_get_products( array(
			'limit'   => 20,
			'orderby' => 'popularity',
			'status'  => 'publish',
		) );

		if ( empty( $products ) ) {
			return "## {$heading}\n\n_No published products yet._\n\n";
		}

		$out = "## {$heading}\n\n";
		foreach ( $products as $product ) {
			$out .= self::product_line( $product );
		}
		$out .= "\n";

		return $out;
	}

	/**
	 * Format a single product as a markdown bullet.
	 */
	private static function product_line( $product ): string {
		$permalink = (string) $product->get_permalink();
		$name      = self::md_link_text( (string) $product->get_name() );
		$short     = wp_strip_all_tags( (string) $product->get_short_description() );
		$short     = wp_trim_words( $short, 40, '…' );
		$price     = $product->get_price();

		$line = "- [{$name}]({$permalink})";
		if ( '' !== $short ) {
			$line .= " — {$short}";
		}
		if ( '' !== $price ) {
			$line .= ' (' . $price . ' ' . get_woocommerce_currency() . ')';
		}

		return $line . "\n";
	}

	private static function section_categories( string $heading = 'Categories' ): string {
		if ( ! taxonomy_exists( 'product_cat' ) ) {
			return '';
		}

		$terms = get_terms( array(
			'taxonomy'   => 'product_cat',
			'hide_empty' => true,
			'number'     => 20,
			'orderby'    => 'count',
			'order'      => 'DESC',
		) );

		if ( is_wp_error( $terms ) || empty( $terms ) ) {
			return '';
		}

		$out = "## {$heading}\n\n";
		foreach ( $terms as $term ) {
			$link = get_term_link( $term );
			if ( is_wp_error( $link ) ) {
				continue;
			}
			$desc = $term->description ? ' — ' . wp_strip_all_tags( $term->description ) : '';
			$out .= '- [' . self::md_link_text( (string) $term->name ) . '](' . $link . "){$desc}\n";
		}
		$out .= "\n";

		return $out;
	}

	private static function section_pages( string $heading = 'Pages' ): string {
		$pages = get_pages( array(
			'sort_column' => 'menu_order',
			'sort_order'  => 'ASC',
			'number'      => 10,
		) );

		if ( empty( $pages ) ) {
			return '';
		}

		$out = "## {$heading}\n\n";
		foreach ( $pages as $page ) {
			$out .= '- [' . self::md_link_text( (string) $page->post_title ) . '](' . get_permalink( $page ) . ")\n";
		}
		$out .= "\n";

		return $out;
	}

	/**
	 * Helpful pointers: sitemap + the complete product index.
	 */
	private static function section_resources( string $heading = 'Site', string $home = '', string $locale = '' ): string {
		$full = '' !== $home ? trailingslashit( $home ) . 'llms-full.txt' : home_url( '/llms-full.txt' );

		$out  = "## {$heading}\n\n";
		$out .= '- Sitemap: ' . self::sitemap_url() . "\n";
		$out .= '- Full product list: ' . $full . "\n";
		if ( '' !== $locale ) {
			$out .= '- Default llms.txt: ' . home_url( '/llms.txt' ) . "\n";
		}
		$out .= "\n";

		return $out;
	}

	private static function section_contact( string $heading = 'Contact', string $home = '' ): string {
		$email = (string) get_option( 'admin_email', '' );
		$store = '' !== $home ? $home : home_url();

		$out = "## {$heading}\n\n";
		if ( '' !== $email ) {
			$out .= "- Email: {$email}\n";
		}
		$out .= "- Store: {$store}\n\n";

		return $out;
	}

	/**
	 * Best available sitemap URL: SEO plugins first, WP core sitemaps last.
	 */
	private static function sitemap_url(): string {
		if ( defined( 'RANK_MATH_VERSION' ) || defined( 'WPSEO_VERSION' ) ) {
			return home_url( '/sitemap_index.xml' );
		}
		return home_url( '/wp-sitemap.xml' );
	}

	/**
	 * Translated section headings for the language variants. Falls back to
	 * English for locales without a mapping.
	 *
	 * @return array{products:string, categories:string, pages:string, site:string, contact:string}
	 */
	private static function lang_headings( string $locale ): array {
		$map = array(
			'zh' => array( 'products' => '产品', 'categories' => '分类', 'pages' => '页面', 'site' => '网站', 'contact' => '联系' ),
			'ja' => array( 'products' => '製品', 'categories' => 'カテゴリ', 'pages' => 'ページ', 'site' => 'サイト', 'contact' => '連絡先' ),
			'fr' => array( 'products' => 'Produits', 'categories' => 'Catégories', 'pages' => 'Pages', 'site' => 'Site', 'contact' => 'Contact' ),
			'de' => array( 'products' => 'Produkte', 'categories' => 'Kategorien', 'pages' => 'Seiten', 'site' => 'Website', 'contact' => 'Kontakt' ),
			'es' => array( 'products' => 'Productos', 'categories' => 'Categorías', 'pages' => 'Páginas', 'site' => 'Sitio', 'contact' => 'Contacto' ),
			'it' => array( 'products' => 'Prodotti', 'categories' => 'Categorie', 'pages' => 'Pagine', 'site' => 'Sito', 'contact' => 'Contatti' ),
			'pt' => array( 'products' => 'Produtos', 'categories' => 'Categorias', 'pages' => 'Páginas', 'site' => 'Site', 'contact' => 'Contato' ),
			'ru' => array( 'products' => 'Товары', 'categories' => 'Категории', 'pages' => 'Страницы', 'site' => 'Сайт', 'contact' => 'Контакты' ),
			'ko' => array( 'products' => '제품', 'categories' => '카테고리', 'pages' => '페이지', 'site' => '사이트', 'contact' => '연락처' ),
		);

		$lang = strtolower( substr( $locale, 0, 2 ) );
		return $map[ $lang ] ?? array(
			'products'   => 'Products',
			'categories' => 'Categories',
			'pages'      => 'Pages',
			'site'       => 'Site',
			'contact'    => 'Contact',
		);
	}

	/**
	 * Locale-aware store URL (Polylang / WPML aware, best effort).
	 */
	private static function lang_home_url( string $locale ): string {
		if ( function_exists( 'pll_home_url' ) ) {
			return (string) pll_home_url( $locale );
		}

		$url = apply_filters( 'wpml_home_url', home_url(), $locale );
		return is_string( $url ) && '' !== $url ? $url : home_url();
	}

	/**
	 * Escape markdown link-text metacharacters so store names can't break
	 * the generated links.
	 */
	private static function md_link_text( string $text ): string {
		return str_replace( array( '[', ']' ), array( '\[', '\]' ), $text );
	}
}
