<?php
/**
 * llms.txt generator.
 *
 * Produces markdown describing the store for AI agents, per the llms.txt spec:
 *   - Line 1: `# <store name>`
 *   - Line 2: `> <short description>`
 *   - Sections for Products, Categories, Pages, About, Contact
 *
 * The content is persisted in `geo_forge_llms_txt` option. The virtual route
 * (`/llms.txt`) serves the option value directly — no regeneration on every
 * request. Re-generate only when:
 *   - Admin clicks "Regenerate" in the editor, OR
 *   - A product/category/page is created/updated/deleted (future milestone).
 *
 * @package GEO_Forge
 */

namespace GEO_Forge\WellKnown;

use GEO_Forge\Log\Logger;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class LlmsTxt {

	private const OPTION = 'geo_forge_llms_txt';

	/**
	 * Render the stored llms.txt content. Returns an empty (but spec-valid)
	 * document if nothing has been generated yet.
	 */
	public static function serve(): string {
		$content = (string) get_option( self::OPTION, '' );

		if ( '' === $content ) {
			$content = self::generate();
		}

		/**
		 * Filter the served llms.txt content.
		 *
		 * Lets site owners or other plugins append/remove sections without
		 * editing the stored option.
		 *
		 * @param string $content The markdown content about to be served.
		 */
		return (string) apply_filters( 'geo_forge_llms_txt_content', $content );
	}

	/**
	 * Generate fresh content from current WooCommerce / WordPress data.
	 * Returns the markdown string. Does NOT persist — caller decides.
	 */
	public static function generate(): string {
		$name        = (string) get_bloginfo( 'name' );
		$description = (string) get_bloginfo( 'description' );
		$url         = home_url();

		$out  = "# {$name}\n";
		$out .= "> {$description}\n\n";

		$out .= self::section_products();
		$out .= self::section_categories();
		$out .= self::section_pages();
		$out .= self::section_contact();

		$out .= "\n---\n";
		$out .= "Generated by GEO Forge on " . current_time( 'Y-m-d' ) . ".\n";

		return $out;
	}

	/**
	 * Generate and persist. Called from the admin "Regenerate" action.
	 */
	public static function regenerate(): string {
		$content = self::generate();
		update_option( self::OPTION, $content );

		Logger::info(
			'llms.txt regenerated.',
			array( 'bytes' => strlen( $content ) )
		);

		return $content;
	}

	/**
	 * Save user-edited content (from the admin editor).
	 * The editor is allowed to produce arbitrary markdown — it's the user's
	 * own store description, served back as-is.
	 */
	public static function save( string $content ): void {
		// Keep the content, but trim trailing whitespace per line.
		$lines = array_map( 'rtrim', explode( "\n", $content ) );
		$content = implode( "\n", $lines );

		update_option( self::OPTION, $content );
		Logger::info( 'llms.txt saved from editor.', array( 'bytes' => strlen( $content ) ) );
	}

	/**
	 * Get the currently stored content (for the admin editor).
	 */
	public static function get_current(): string {
		return (string) get_option( self::OPTION, '' );
	}

	/* =================================================================
	 * Section builders
	 * ================================================================ */

	private static function section_products(): string {
		if ( ! function_exists( 'wc_get_products' ) ) {
			return "## Products\n\n_WooCommerce not active._\n\n";
		}

		$products = wc_get_products( array(
			'limit'   => 20,
			'orderby' => 'popularity',
			'status'  => 'publish',
		) );

		if ( empty( $products ) ) {
			return "## Products\n\n_No published products yet._\n\n";
		}

		$out  = "## Products\n\n";
		foreach ( $products as $product ) {
			$permalink = $product->get_permalink();
			$name      = $product->get_name();
			$short     = wp_strip_all_tags( (string) $product->get_short_description() );
			$short     = mb_substr( $short, 0, 200 );
			$price     = $product->get_price();

			$line = "- [{$name}]({$permalink})";
			if ( '' !== $short ) {
				$line .= " — {$short}";
			}
			if ( '' !== $price ) {
				$line .= " ({$price} " . get_woocommerce_currency() . ')';
			}
			$out .= $line . "\n";
		}
		$out .= "\n";

		return $out;
	}

	private static function section_categories(): string {
		if ( ! taxonomy_exists( 'product_cat' ) ) {
			return '';
		}

		$terms = get_terms( array(
			'taxonomy'   => 'product_cat',
			'hide_empty' => true,
			'number'     => 20,
			'orderby'    => 'count',
			'order'      => 'DESC',
		) );

		if ( is_wp_error( $terms ) || empty( $terms ) ) {
			return '';
		}

		$out  = "## Categories\n\n";
		foreach ( $terms as $term ) {
			$link = get_term_link( $term );
			if ( is_wp_error( $link ) ) {
				continue;
			}
			$desc = $term->description ? ' — ' . wp_strip_all_tags( $term->description ) : '';
			$out .= "- [{$term->name}]({$link}){$desc}\n";
		}
		$out .= "\n";

		return $out;
	}

	private static function section_pages(): string {
		$pages = get_pages( array(
			'sort_column' => 'menu_order',
			'sort_order'  => 'ASC',
			'number'      => 10,
		) );

		if ( empty( $pages ) ) {
			return '';
		}

		$out = "## Pages\n\n";
		foreach ( $pages as $page ) {
			$out .= "- [{$page->post_title}](" . get_permalink( $page ) . ")\n";
		}
		$out .= "\n";

		return $out;
	}

	private static function section_contact(): string {
		$email = (string) get_option( 'admin_email', '' );
		$out   = "## Contact\n\n";
		if ( '' !== $email ) {
			$out .= "- Email: {$email}\n";
		}
		$out .= "- Store: " . home_url() . "\n\n";
		return $out;
	}
}
